= ez-jamulus-server

This is a script to install a headless Jamulus Server on a Debian cloud VM.

It is created for people who have little to no Linux administration knowledge.

NOTE: This script is not maintained (it may be out of date). Please feel free to fork this project. If someone does, I will be very happy to direct people to that project.

== Install script

https://raw.githubusercontent.com/dtinth/ez-jamulus-server/main/script.txt[Here is the installation script.] Open it, copy and paste it into an SSH session (e.g. PuTTY window).

== Configuration

After running any of these commands, re-run the install script above for changes to take effect.

=== Change server name, city, country

 echo 'NAME;CITY;0' | sudo tee /etc/jamulus-server-info

* [ ] Replace `NAME` with your server name.
* [ ] Replace `CITY` with your city.
* [ ] Replace `0` with your country ID https://doc.qt.io/qt-5/qlocale.html#Country-enum[from this list].

=== Change welcome message

 echo 'welcome to my server' | sudo tee /etc/jamulus-welcome-message

=== Change number of max users

 echo 16 | sudo tee /etc/jamulus-max-users

=== Make server private

 sudo touch /etc/jamulus-private

=== Make server public

 sudo rm -f /etc/jamulus-private

=== Change server genre

.Any Genre 1
 echo 'anygenre1.jamulus.io:22124' | sudo tee /etc/jamulus-directory-server

.Any Genre 2
 echo 'anygenre2.jamulus.io:22224' | sudo tee /etc/jamulus-directory-server

.Any Genre 3
 echo 'anygenre3.jamulus.io:22624' | sudo tee /etc/jamulus-directory-server

.Genre Rock
 echo 'rock.jamulus.io:22424' | sudo tee /etc/jamulus-directory-server

.Genre Jazz
 echo 'jazz.jamulus.io:22324' | sudo tee /etc/jamulus-directory-server

.Genre Classical/Folk
 echo 'classical.jamulus.io:22524' | sudo tee /etc/jamulus-directory-server

.Genre Choral/Barbershop
 echo 'choral.jamulus.io:22724' | sudo tee /etc/jamulus-directory-server

IMPORTANT: Do not forget to run the install script again for changes to take effect.

== Logs

 journalctl -u jamulus-headless

See https://jamulus.io/wiki/Server-Linux#viewing-the-logs[the official Jamulus documentation] for more information.

== Cloud providers

It has been tested on the following Cloud Providers:

* Huawei Cloud
* Bangmod.Cloud
* DigitalOcean
* Linode

== Troubleshooting

=== “sudo: command not found”

----
-bash: sudo: command not found
...
Cannot write to '-' (Broken pipe).
----

Run this command and try out the installation script again:

 apt update --allow-releaseinfo-change -y
 apt install -y sudo