= ez-jamulus-server

This is an script to install a headless Jamulus Server on a Debian cloud VM.

It is created for people who have little to no Linux administration knowledge.

NOTE: This script is not maintained (it may be out of date). Please feel free to fork this project. If someone does, I will be very happy to direct people to that project.

== Install script

https://raw.githubusercontent.com/dtinth/ez-jamulus-server/main/script.txt[Here is the installation script.] Open it, copy and paste it into an SSH session (e.g. PuTTY window).

== Configuration

After running any of these commands, re-run the install script above for changes to take effect.

=== Change server name, city, country

 echo 'NAME;CITY;0' | sudo tee /etc/jamulus-server-info

=== Change welcome message

 echo 'welcome to my server' | sudo tee /etc/jamulus-welcome-message

=== Change number of max users

 echo 16 | sudo tee /etc/jamulus-max-users

=== Make server private

 sudo touch /etc/jamulus-private

=== Make server public

 sudo rm -f /etc/jamulus-private

IMPORTANT: Do not forget to run the install script again for changes to take effect.
